radio-button v1
traboda/design-system pull request #45
Opened 2023-01-26 09:35 UTC by abhikrishnaram

![image](https://user-images.githubusercontent.com/66553902/214801010-72f423b5-ec8a-4243-9008-8d84a5ca1137.png)
![image](https://user-images.githubusercontent.com/66553902/214801138-d29a8bda-fcb2-4897-aa56-a3657015c8af.png)

2023-01-26 10:44 UTC, Advaith3600 requested changes

2023-01-26 10:44 UTC, Advaith3600 commented on src/index.ts
> +export { default as RadioGroup } from './components/Radio/RadioGroup';
Export single Radio Element as well

2023-01-26 10:44 UTC, Advaith3600 commented on src/components/Radio/Radio.tsx
> +          <span className={clsx(['dsr-ml-2', size?.label && `dsr-text-${size?.label}`])}>{option.label}</span>
`dsr-text-${size?.label}` - tailwind css JIT won't work with string interpolation, define the classes properly

2023-01-26 10:44 UTC, Advaith3600 commented on src/components/Radio/Radio.tsx
> +          <span className={clsx(['dsr-ml-2', size?.label && `dsr-text-${size?.label}`])}>{option.label}</span>
Accessibility: When you click on the label will it select the radio button? If not have to do it

2023-01-26 10:44 UTC, Advaith3600 commented on src/components/Radio/Radio.tsx
> +                'dsr-border-inherit dsr-text-white', size?.button, isChecked && styled.radioButton,
make it multiline

2023-01-26 10:44 UTC, Advaith3600 commented on src/components/Radio/radio.module.scss
> +  &:before {
`&::before` not `&:before`

2023-01-26 10:46 UTC, Advaith3600 commented
Why does such an approach require such a simple design? 

You can use `accent-color` property of CSS for this and do absolute no madness

2023-01-26 14:26 UTC, abhikrishnaram commented
> Why does such an approach require such a simple design?
> 
> You can use `accent-color` property of CSS for this and do absolute no madness

This approach uses a custom radio button instead of modifying the default HTML style. This approach I believe, gives us the ability to customize and modify completely as much as we require.

2023-01-27 13:21 UTC, Advaith3600 approved these changes

2023-01-27 13:22 UTC, merged